sudo: false
language: go

os:
- linux
  #- osx

env:
- ARCH=x84_64
- ARCH=i686


go:
- 1.6

before_script:
- go get -u github.com/client9/misspell/cmd/misspell
script:
- diff -au <(gofmt -d .) <(printf "")
- go vet ./...
- misspell cmd/*

